### ISSUE TITLE
Example 8 not working

### ISSUE THREAD

**Issue by rayzchen** [rayzchen/pyunity#1]
Example 8 gives error:

```
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyunity\__main__.py", line 2, in <module>
    examples.show()
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyunity\examples\__init__.py", line 28, in show
    example_list[num - 1].main()
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyunity\examples\example8\__init__.py", line 9, in main
    clip = AudioClip(os.path.join(path, "explode.ogg"))
  File "audio.py", line 46, in pyunity.audio.AudioClip.__init__
  File "audio.py", line 77, in pyunity.audio.AudioClip.SetSound
pyunity.errors.PyUnityException: Cannot find file: C:\Users\D\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pyunity\examples\example8\explode.ogg
```

It is caused by the lack of an `else` statement for checking if the file exists. Also, the OGG file does not get included in the source and wheels.

**Comment by rayzchen** [comment]
It is now fixed in v0.2.1.
