### ISSUE TITLE
Cannot import when built with Cython

### ISSUE THREAD

**Issue by rayzchen** [rayzchen/pyunity#2]
In the current state, importing PyUnity will cause this error:

```
Loaded config
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyunity\__init__.py", line 125, in <module>
    from .audio import *
  File "audio.py", line 12, in init pyunity.audio
  File "config.py", line 17, in init pyunity.config
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyunity\window\__init__.py", line 34, in <module>
    from .glutWindow import Window as glutWindow
ImportError: DLL load failed while importing glutWindow: The specified module could not be found.
```

**Comment by rayzchen** [comment]
A notice has been added to the documentation on the main page.

**Comment by rayzchen** [comment]
I have fixed it, but now the GLUT window is not centered. Funnily enough, this error has only happened on one computer.

**Comment by rayzchen** [comment]
Its been a very long time :) better close this as that computer was very messed up anyways.
