### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by rayzchen** [rayzchen/pyunity#7]
Cannot import pyunity due to error below:
```
Loaded config
Trying GLFW as a window provider
Using window provider GLFW
Traceback (most recent call last):
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\raych\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyunity\__init__.py", line 156, in <module>
    from .audio import *
  File "audio.py", line 13, in init pyunity.audio
  File "core.py", line 1, in init pyunity.core
ModuleNotFoundError: No module named 'vector3'
```

**Comment by rayzchen** [comment]
Seems that the error goes as far back as 5 commits before 0.3.0... i remember clearly that the bug was not there then ¯\_(ツ)_/¯
Maybe it was my environment or something, testing with virtualenv now

**Comment by rayzchen** [comment]
NOPE that didn't work out at all

**Comment by rayzchen** [comment]
Last working commit that i have tested: 8230364

**Comment by rayzchen** [comment]
The commit that seems to have introduced this error is 98f9918, I'm going to check to see if any changes caused it

**Comment by rayzchen** [comment]
Comparison: https://github.com/rayzchen/pyunity/compare/63054d8...98f9918

**Comment by rayzchen** [comment]
The most changed file is `glfwWindow.py`

**Comment by rayzchen** [comment]
Seems that 63054d8 doesnt work too

**Comment by rayzchen** [comment]
YES FINALLY found the two commits:

https://github.com/rayzchen/pyunity/compare/dbd20a6...a0f39e6

**Comment by rayzchen** [comment]
I think the reason is because of the PXD files (line 1 references from `.vector3 cimport Vector3`)

**Comment by rayzchen** [comment]
As of now, the PXD files have been disabled. However, a branch named `patch-1` is going to experiment with fixing the bug. This issue will be closed.
